services:
  - type: web
    name: zona-kino-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CURRENCY_SYMBOL
        value: "сум"
      - key: SUBSCRIPTION_PRICE
        value: "25000"
      - key: SUBSCRIPTION_DAYS
        value: "30"
      - key: CARD_NUMBER
        value: "8600 0000 0000 0000"
      - key: CARD_BANK
        value: "Uzcard / Humo"
      - key: CARD_HOLDER
        value: "Имя Получателя"
      - key: CINEMA_URL
        value: "https://msx.zona.ms/"
      - key: KEEP_ALIVE
        value: "true"
      - key: PING_INTERVAL
        value: "600"
